### ISSUE TITLE
Why you don't use template string?

### ISSUE THREAD

**Issue by h4wldev** [therne/cottage#15]
https://github.com/therne/cottage/blob/f08ac325270a32b39df7a258d751ded5280fe73b/lib/response.js#L16

I think 
```javascript
if (!pre) throw Error(`response '${key}' is not predefined. (you can use Response.define)`);
```
is better than
```javascript
if (!pre) throw Error("response '" + key + "' is not predefined. (you can use Response.define)"); 
```

Reference: [Airbnb Lint - es6 template string](https://github.com/airbnb/javascript#es6-template-literals)

**Comment by therne** [comment]
Oh I forgot it :) thanks!
