### ISSUE TITLE
Update examples to Cottage v3

### ISSUE THREAD

**Issue by cavejay** [therne/cottage#21]
Attempting to figure out how to capture params from the URL with v3. There's currently sparse documentation on this at the moment and the examples in the repo are for a previous version. 

I'm currently experimenting with how I can access the params, but in the absence of me figuring that out can you please update the documentation or comment on this issue?

**Comment by cavejay** [comment]
Params are captured in `ctx.request.params` and that's a very logical place for them to be. If I get time/motivation I may attempt to update the examples and provide a Pull Request.

**Comment by therne** [comment]
Sorry, I'll take care of the documentations and examples 😢 Thanks!
